/** sha256 of each bundled payload-markdown skill variant (generated by scripts/generate-skill-manifest.mjs). */
export const PAYLOAD_MARKDOWN_SKILL_SHA256 = {
  claude: 'cc10d5c520f7a23d449ae88dc27cc312169fcc81100e8bd820555177ae78e6c6',
  codex: '636193135fec55d0ddaffe27f8b33389fdad73616459ae7d1b783c14654d9181',
} as const
