/** sha256 of each bundled payload-markdown skill variant (generated by scripts/generate-skill-manifest.mjs). */
export const PAYLOAD_MARKDOWN_SKILL_SHA256 = {
  claude: '944ae5d92e535e8972da85fd157743ac07659a7512104dd43e93a59035e9a1f2',
  codex: '999e001d45286c4fb263d0cfacf9ece369fceb40e91fc1805d18595436745008',
} as const
