#!/usr/bin/env node
/**
 * Writes src/version.ts from package.json. Run after bumping the package
 * version (`pnpm sync:version`); `dev/settings.int.spec.ts` fails while the
 * two disagree.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const { version } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
const target = path.join(root, 'src/version.ts')
const source = `/** Version of this copy of payload-markdown (generated by scripts/sync-version.mjs). */
export const PAYLOAD_MARKDOWN_VERSION = '${version}'
`

if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== source) {
  fs.writeFileSync(target, source)
  console.log(`src/version.ts -> ${version}`)
}
